"""2nd migration

Revision ID: 4eafaec2fc4d
Revises: 417b9a1da544
Create Date: 2025-06-16 11:57:58.601504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4eafaec2fc4d'
down_revision: Union[str, None] = '417b9a1da544'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('event_type_4', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'event_type_4')
    # ### end Alembic commands ###
